# Generated by Django 4.2.5 on 2023-10-11 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('symptoms', models.TextField(blank=True, verbose_name='Симптомы')),
            ],
            options={
                'verbose_name': 'Здоровье',
                'verbose_name_plural': 'Здоровье',
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('year_of_creation', models.DateField(blank=True, verbose_name='Год создания')),
                ('number_of_animals', models.IntegerField(verbose_name='Количество животных')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/shelter/%Y/%m/%d/', verbose_name='Фото')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('contacts', models.CharField(max_length=11, verbose_name='Контакты')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
            ],
            options={
                'verbose_name': 'Приют',
                'verbose_name_plural': 'Приюты',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('gender', models.BooleanField(choices=[(True, 'Мужской'), (False, 'Женский')], verbose_name='Пол')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('height', models.IntegerField(verbose_name='Рост')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('owner', models.BooleanField(verbose_name='Был ли хозяин')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Окрас')),
                ('photo', models.ImageField(blank=True, upload_to='photos/dog/%Y/%m/%d/', verbose_name='Фото')),
                ('breed', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainPage.breed', verbose_name='Название породы')),
                ('health', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainPage.health', verbose_name='Здоровье')),
                ('shelter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='MainPage.shelter', verbose_name='Приют')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
            },
        ),
    ]
