# Generated by Django 4.2.5 on 2023-10-12 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/dog/%Y/%m/%d/', verbose_name='Фото')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.dog', verbose_name='собака')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='photos',
            field=models.ManyToManyField(related_name='dogs', to='MainPage.dogphoto'),
        ),
    ]
