# Generated by Django 4.2.5 on 2023-10-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_dogphoto_dog_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='photo',
        ),
    ]
