# Generated by Django 4.2.5 on 2023-10-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_remove_dog_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='photos',
        ),
        migrations.AddField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/dog/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='DogPhoto',
        ),
    ]
