# Generated by Django 4.2.5 on 2023-10-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_remove_dog_photos_dog_photo_delete_dogphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], verbose_name='Был ли хозяин'),
        ),
        migrations.CreateModel(
            name='DogPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, upload_to='photos/moredog/%Y/%m/%d/', verbose_name='Фото')),
                ('dog', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='MainPage.dog', verbose_name='Собака')),
            ],
        ),
    ]
