# Generated by Django 4.2.5 on 2023-10-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0005_alter_dog_owner_dogphotos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DogPhotos',
        ),
    ]
