# Generated by Django 5.0 on 2024-02-23 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0007_shelterphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job', to='MainPage.shelter', verbose_name='Место работы'),
        ),
    ]
